name = "odd_support_filtration"
version = "0.1.0"
defaultTargets = ["OddSupportFiltration"]

[[lean_lib]]
name = "OddSupportFiltration"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.32.2"
